### ISSUE TITLE
Rename resource from ...metadata to ...profile

### ISSUE THREAD

**Issue by nicholascar** [CSIRO-enviro-informatics/eudm-dataset#1]
Can we establish a new convention of naming profiles ...profile, like we would name an ontology ...ontology? The eudm-*metadata* naming is ambiguous: it's more a profile thing than a metadata thing.

**Comment by dr-shorthair** [comment]
I disagree with -profile. According to Rob's model _everything_ is a profile (in the base case a 'null' profile) so -profile naming adds nothing useful. 

A suffix is needed since I imagine this won't be the only EUDM vocabulary, and I provisionally chose -metadata but would be OK with something else as long as it is consistent with the scope of the package. 
Maybe eudm-dataset ? (My expectation is that the backbone will be DCAT.)

**Comment by dr-shorthair** [comment]
@nicholascar I disagree with your thinking on names, and explained why in the comment above. If you have a counter-argument them I'm happy to hear it, but it is inappropriate to make the change until we've reached a consensus on the issue.

**Comment by nicholascar** [comment]
OK, understand the no value of naming something a profile. Prefer eudm-dataset over eudm-metadata as it's specific to the thing this work is for, the datasets. Happy for you to rename.
